import type { Metadata } from "next";
import {  Luckiest_Guy } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const LuckiestGuy = Luckiest_Guy({
  subsets: ["latin"],
  variable: "--font-luckiest-guy",
  weight: "400"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${LuckiestGuy.variable}  h-full antialiased`}
    >
     
      <body className="min-h-full flex flex-col">
         <NavBar/>
        {children}</body>
    </html>
  );
}
